<!-- # --- -->
<!-- # title: "Bayesiand Data Analysis Project" -->
<!-- # subtitle: "Credit Score Analysis" -->
<!-- # author: anonymous # <-- hand in anonymously -->
<!-- # output:  -->
<!-- #   pdf_document:  -->
<!-- #     toc: false -->
<!-- # bibliography: references.bib  -->
<!-- # --- -->

```{r include=FALSE}
library(tibble)
library(rstan)
library(cmdstanr)
library(ggplot2)
library(loo)
library(bayesplot)
library(gridExtra)
library(dplyr)
library(grid)


set.seed(10)
```

```{r}
data <- read.csv("credit_score.csv")
data <- data[,3:ncol(data)-1]

cat_gampling <- data$CAT_GAMBLING
cat_gampling <- ifelse(cat_gampling == "No", 0, ifelse(cat_gampling == "Low", 1, 2))

data <- data[,!grepl("GROCERIES|CLOTHING|HOUSING|EDUCATION|HEALTH|TRAVEL|ENTERTAINMENT|GAMBLING|UTILITIES|TAX|FINES", colnames(data))]
data <- data[,!grepl("R_", colnames(data))]

data <- add_column(data, CAT_GAMBLING=cat_gampling, .before = length(data))
n_features <- length(data)-1
head(data)
```   

```{r}
library(corrplot)
par(bg=NA)
corrplot(cor(data[, 1:5]), method = 'color',  tl.col = 'black', tl.pos='ld', type='lower')
```


```{r}
# create histogram of INCOME, DEBT, and SAVING side by side  column of data
par(mfrow = c(1,3), bg=NA)
hist(data$INCOME, main = "Income", xlab = "Income")
hist(data$DEBT, main = "Debt", xlab = "Debt")
hist(data$SAVING, main = "Saving", xlab = "Saving")
```

```{r}
par(bg=NA)
hist(data$CREDIT_SCORE, main = "Credit Score", xlab = "Credit Score")
```

```{r}
# create piechart of all columns containing the word "CAT" in a 3 by 2 plots
par(mfrow = c(3,2), mar=c(1, 1, 1, 1), bg=NA)

for (i in 1:ncol(data)){
  if (grepl("CAT", colnames(data)[i])){
    pie(table(data[,i]), main = colnames(data)[i], radius=1) 
  }
}
```

```{r}
# create a scatter plot of INCOME vs DEBT
par(bg=NA)
plot(data$INCOME, data$DEBT, xlab = "Income", ylab = "Debt", main = "Income vs Debt")
```

```{r}
# Standardize columns of data except last column
data_normalized <- data
data_normalized[1:(length(data)-1)] <- as.data.frame(scale(data[1:(length(data)-1)]))

# Separate data into three parts for each CAT_GAMBLING value
data_0 <- data_normalized[data$CAT_GAMBLING == 0,]
data_1 <- data_normalized[data$CAT_GAMBLING == 1,]
data_2 <- data_normalized[data$CAT_GAMBLING == 2,]
```

```{r}
stan_data <- list(
                  N1=nrow(data_0),
                  N2=nrow(data_1),
                  N3=nrow(data_2),
                  N_features=n_features,
                  x1=data_0[1:n_features],
                  x2=data_1[1:n_features],
                  x3=data_2[1:n_features],
                  y1=data_0[['CREDIT_SCORE']],
                  y2=data_1[['CREDIT_SCORE']],
                  y3=data_2[['CREDIT_SCORE']]
                  )
```

```{r}
separate_model = cmdstan_model("./Separate.stan")
out <- capture.output(
  separate_fit <- separate_model$sample(data=stan_data, refresh=0, show_messages=FALSE)
)
separate_summary = separate_fit$summary()
separate_summary
```

```{r}
hierarchical_model = cmdstan_model("./Hierarchical.stan")
out <- capture.output(
  hier_fit <- hierarchical_model$sample(data=stan_data,
                                        chains=4,
                                        iter_sampling=2000,
                                        iter_warmup=1000,
                                        refresh=0,
                                        show_messages=FALSE)
)

hier_summary = hier_fit$summary()
hier_summary
```

```{r}
print(sum(separate_summary$rhat>1.01))
print(sum(hier_summary$rhat>1.01))
```

```{r}
separate_fit$diagnostic_summary(diagnostics=c("divergences", "treedepth"))
```
```{r}
hier_fit$diagnostic_summary(diagnostics=c("divergences", "treedepth"))
```
```{r}
print(sum(separate_summary$ess_bulk<400))
print(sum(hier_summary$ess_bulk<400))
```


```{r}
separate_fit$cmdstan_diagnose()
```

```{r}
hier_fit$cmdstan_diagnose()
```


```{r}
sep1 <- ppc_dens_overlay(data_0$CREDIT_SCORE,
                         separate_fit$draws("y1_rep", format="matrix")[sample(4000, 100), ]) + 
  ggtitle('Separate') + 
  theme(plot.title = element_text(hjust = 0.5), plot.background=element_blank(),panel.grid.major=element_blank(), panel.grid.minor = element_blank()
          ) +
  theme(
        panel.background = element_rect(fill = "transparent",colour = NA), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank()) +
  ylab('Gambling None')


sep2 <- ppc_dens_overlay(data_1$CREDIT_SCORE,
                         separate_fit$draws("y2_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Gambling Low')


sep3 <- ppc_dens_overlay(data_2$CREDIT_SCORE,
                         separate_fit$draws("y3_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Gambling High') +
  xlab('Credit Score')


hier1 <- ppc_dens_overlay(data_0$CREDIT_SCORE,
                          hier_fit$draws("y1_rep", format="matrix")[sample(4000, 100), ]) + 
  ggtitle('Hierarchical') + 
  theme(plot.title = element_text(hjust = 0.5))

hier2 <- ppc_dens_overlay(data_1$CREDIT_SCORE,
                          hier_fit$draws("y2_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5))


hier3 <- ppc_dens_overlay(data_2$CREDIT_SCORE,
                          hier_fit$draws("y3_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab('Credit Score')

```

```{r echo=FALSE, fig.height=6, fig.width=8}
# tg <- textGrob('', gp=gpar(fontsize=16, fontface='bold'))
# g <- grid.arrange(sep1, hier1, sep2, hier2, sep3, hier3, ncol=2, nrow=3, top=tg)

g2 <- cowplot::plot_grid(sep1, hier1, sep2, hier2, sep3, hier3, ncol=2, nrow=3) + 
  theme(plot.background = element_rect(fill="transparent"))

# check the plot
plot(g2)
# save it as png
ggsave("posterior.png", g2, bg="transparent")
```

```{r}
 separate_narrow_alpha_model = cmdstan_model("./Separate_narrow_alpha.stan")
 out <- capture.output(
   separate_narrow_alpha_fit <- separate_narrow_alpha_model$sample(data=stan_data, refresh=0, show_messages=FALSE)
 )
 separate_narrow_alpha_summary = separate_narrow_alpha_fit$summary()
```
```{r}
separate_narrow_beta_model = cmdstan_model("./Separate_narrow_beta.stan")
out <- capture.output(
  separate_narrow_beta_fit <- separate_narrow_beta_model$sample(data=stan_data, refresh=0, show_messages=FALSE)
)
separate_narrow_beta_summary = separate_narrow_beta_fit$summary()
```
```{r}
hierarchical_narrow_alpha_model = cmdstan_model("./Hierarchical_narrow_alpha.stan")
out <- capture.output(
  hier_narrow_alpha_fit <- hierarchical_narrow_alpha_model$sample(data=stan_data, refresh=0, show_messages=FALSE)
)

hier_narrow_alpha_summary = hier_narrow_alpha_fit$summary()
```

```{r}
hierarchical_narrow_beta_model = cmdstan_model("./Hierarchical_narrow_beta.stan")
out <- capture.output(
  hier_narrow_beta_fit <- hierarchical_narrow_beta_model$sample(data=stan_data, refresh=0, show_messages=FALSE)
)

hier_narrow_beta_summary = hier_narrow_beta_fit$summary()
```



```{r}
print(sum(separate_narrow_alpha_summary$rhat>1.01))
separate_narrow_alpha_fit$diagnostic_summary(diagnostics=c("divergences", "treedepth"))
```
```{r}
print(sum(separate_narrow_beta_summary$rhat>1.01))
separate_narrow_beta_fit$diagnostic_summary(diagnostics=c("divergences", "treedepth"))
```
```{r}
print(sum(hier_narrow_alpha_summary$rhat>1.01))
hier_narrow_alpha_fit$diagnostic_summary(diagnostics=c("divergences", "treedepth"))
```

```{r}
print(sum(hier_narrow_beta_summary$rhat>1.01))
hier_narrow_beta_fit$diagnostic_summary(diagnostics=c("divergences", "treedepth"))
```

```{r}
separate_narrow_alpha_fit$cmdstan_diagnose()
```
```{r}
separate_narrow_beta_fit$cmdstan_diagnose()
```
```{r}
hier_narrow_alpha_fit$cmdstan_diagnose()
```

```{r}
hier_narrow_beta_fit$cmdstan_diagnose()
```









```{r}
sep_na1 <- ppc_dens_overlay(data_0$CREDIT_SCORE,
                         separate_narrow_alpha_fit$draws("y1_rep", format="matrix")[sample(4000, 100), ]) + 
  ggtitle('Separate Narrow Alpha') + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Gambling None')


sep_na2 <- ppc_dens_overlay(data_1$CREDIT_SCORE,
                         separate_narrow_alpha_fit$draws("y2_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Gambling Low')


sep_na3 <- ppc_dens_overlay(data_2$CREDIT_SCORE,
                         separate_narrow_alpha_fit$draws("y3_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Gambling High') +
  xlab('Credit Score')


hier_na1 <- ppc_dens_overlay(data_0$CREDIT_SCORE,
                          hier_narrow_alpha_fit$draws("y1_rep", format="matrix")[sample(4000, 100), ]) + 
  ggtitle('Hierarchical Narrow Alpha') + 
  theme(plot.title = element_text(hjust = 0.5))

hier_na2 <- ppc_dens_overlay(data_1$CREDIT_SCORE,
                          hier_narrow_alpha_fit$draws("y2_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5))


hier_na3 <- ppc_dens_overlay(data_2$CREDIT_SCORE,
                          hier_narrow_alpha_fit$draws("y3_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab('Credit Score')
```

```{r echo=FALSE, fig.height=6, fig.width=8}
tg <- textGrob('', gp=gpar(fontsize=16, fontface='bold'))
grid.arrange(sep_na1, hier_na1, sep_na2, hier_na2, sep_na3, hier_na3, ncol=2, nrow=3, top=tg)
```

```{r}
sep_nb1 <- ppc_dens_overlay(data_0$CREDIT_SCORE,
                         separate_narrow_beta_fit$draws("y1_rep", format="matrix")[sample(4000, 100), ]) + 
  ggtitle('Separate Narrow Beta') + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Gambling None')


sep_nb2 <- ppc_dens_overlay(data_1$CREDIT_SCORE,
                         separate_narrow_beta_fit$draws("y2_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Gambling Low')


sep_nb3 <- ppc_dens_overlay(data_2$CREDIT_SCORE,
                         separate_narrow_beta_fit$draws("y3_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Gambling High') +
  xlab('Credit Score')


hier_nb1 <- ppc_dens_overlay(data_0$CREDIT_SCORE,
                          hier_narrow_beta_fit$draws("y1_rep", format="matrix")[sample(4000, 100), ]) + 
  ggtitle('Hierarchical Narrow Beta') + 
  theme(plot.title = element_text(hjust = 0.5))

hier_nb2 <- ppc_dens_overlay(data_1$CREDIT_SCORE,
                          hier_narrow_beta_fit$draws("y2_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5))


hier_nb3 <- ppc_dens_overlay(data_2$CREDIT_SCORE,
                          hier_narrow_beta_fit$draws("y3_rep", format="matrix")[sample(4000, 100), ]) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab('Credit Score')
```

```{r echo=FALSE, fig.height=6, fig.width=8}
tg <- textGrob('', gp=gpar(fontsize=16, fontface='bold'))
grid.arrange(sep_nb1, hier_nb1, sep_nb2, hier_nb2, sep_nb3, hier_nb3, ncol=2, nrow=3, top=tg)
```

```{r}
loo_hier <- loo(hier_fit$draws("log_lik"))
loo_sep <- loo(separate_fit$draws("log_lik"))
loo_hier_na <- loo(hier_narrow_alpha_fit$draws("log_lik"))
loo_sep_na <- loo(separate_narrow_alpha_fit$draws("log_lik"))
loo_hier_nb <- loo(hier_narrow_beta_fit$draws("log_lik"))
loo_sep_nb <- loo(separate_narrow_beta_fit$draws("log_lik"))


loo_compare(loo_hier, loo_hier_na, loo_hier_nb, loo_sep, loo_sep_na, loo_sep_nb)

```
```{r}
plot(loo_sep, label_points = TRUE)
```
```{r}
plot(loo_sep_na, label_points = TRUE)
```

```{r}
plot(loo_sep_nb, label_points = TRUE)
```
 
```{r}
plot(loo_hier, label_points = TRUE)
```

```{r}
plot(loo_hier_na, label_points = TRUE)
```

```{r}
plot(loo_hier_nb, label_points = TRUE)
```



```{r}
print(mean(hier_fit$draws("alpha1")))
print(apply(hier_fit$draws("beta1"), c(3), mean))

print(mean(hier_fit$draws("alpha2")))
print(apply(hier_fit$draws("beta2"), c(3), mean))

print(mean(hier_fit$draws("alpha3")))
print(apply(hier_fit$draws("beta3"), c(3), mean))


```

```{r}
hierarchical_model_new = cmdstan_model("./Hierarchical.stan")
out <- capture.output(
  hier_fit_new <- hierarchical_model_new$sample(data=stan_data,
                                                chains=8, iter_sampling=3000, iter_warmup=2000,
                                                refresh=0, show_messages=FALSE)
)

hier_summary_new = hier_fit_new$summary()
hier_summary_new
```


```{r}
hier_fit_new$cmdstan_diagnose()
```
